server:
  port: 7004
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
zuul:
  prefix: /api    #添加路由前缀
  routes:
    i-cloud-auth: /i-cloud-auth/**
    i-cloud-rbac: /i-cloud-rbac/**
  host:
    max-per-route-connections: 60000
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000
  add-host-header: true
  sensitive-headers:
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
#TokenFilter白名单URL
filter:
  token:
    white-uris: "/api/i-cloud-auth/**,/api/i-cloud-rbac/user/info,**option**,/*/**"